version: '3.9'

services:

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - CORE_URL=http://host.docker.internal:5000  # URL para acessar o SD_core na máquina host
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Permite que o container acesse o host

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
