version: '3.8'

services:

# === RABBITMQ LOCAL (opcional) ===
  # Descomente isso se quiser usar RabbitMQ no mesmo docker-compose
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"  # painel de admin
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq
  #   networks:
  #     - voting-network
  #     - rede
  #   healthcheck:
  #     test: ["CMD", "rabbitmq-diagnostics", "ping"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  # === BACKEND FLASK ===
  backend:
    build: ./backend
    container_name: voting-backend
    ports:
      - "5001:5001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - voting-network
      - rede
    restart: unless-stopped

  # === FRONTEND ANGULAR ===
  frontend:
    build: ./frontend
    container_name: voting-frontend
    ports:
      - "0.0.0.0:4200:80"
    depends_on:
      - backend
    networks:
      - voting-network
    restart: unless-stopped


# === REDES ===
networks:
  voting-network:
    driver: bridge
  rede:
    external: true
    name: rede  # mesma rede usada pelo core

# === VOLUMES ===
# volumes:
#   rabbitmq_data:
