FROM python:3.10-slim

WORKDIR /app

# Definir variáveis de ambiente
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# Instalar dependências do sistema (se necessário)
RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Copiar e instalar dependências Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt



# Copiar o resto do código da aplicação
COPY . .

# VERIFICAÇÃO: Listar arquivos no diretório de trabalho para depuração
RUN ls -l .

# Expor a porta que a aplicação usa
EXPOSE 5001

# Comando para executar a aplicação com waitress e modo "unbuffered"
CMD ["python", "-u", "app.py"]