apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: voting-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-kafka
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z kafka 9092; do echo waiting for kafka; sleep 2; done;']
      containers:
      - name: backend
        image: voting-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: CORE_URL
          value: "http://host.docker.internal:5000"
        - name: KAFKA_BROKER
          value: "kafka:9092"
        readinessProbe:
          httpGet:
            path: /candidatos  # ou qualquer endpoint que funcione
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /candidatos
            port: 5001
          initialDelaySeconds: 20
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: voting-system
spec:
  selector:
    app: backend
  ports:
  - port: 5001
    targetPort: 5001
  type: LoadBalancer