apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: voting-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: voting-frontend:latest
        imagePullPolicy: Never  # Para usar imagem local
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: voting-system
spec:
  selector:
    app: frontend
  ports:
  - port: 4200
    targetPort: 80
  type: LoadBalancer  # Expõe externamente